# Generated by Django 4.0.4 on 2022-04-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='REP_EMPRESA',
            fields=[
                ('ID_EMPRESA', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE_EMPRESA', models.CharField(max_length=50)),
                ('NIT', models.CharField(max_length=15)),
                ('CODIGO', models.CharField(max_length=15)),
                ('DIRECCION', models.CharField(max_length=50)),
                ('TELEFONO', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='REP_PERSONA',
            fields=[
                ('ID_PERSONA', models.AutoField(primary_key=True, serialize=False)),
                ('DPI', models.CharField(max_length=20)),
                ('PRIMER_NOMBRE', models.CharField(max_length=50)),
                ('SEGUNDO_NOMBRE', models.CharField(max_length=50)),
                ('PRIMER_APELLIDO', models.CharField(max_length=50)),
                ('SEGUNDO_APELLIDO', models.CharField(max_length=50)),
                ('APELLIDO_CASADA', models.CharField(max_length=50)),
                ('ORDEN_CEDULA', models.CharField(max_length=50)),
                ('REGISTRO_DEDULA', models.CharField(max_length=50)),
                ('DIRECCION_RESIDENCIA', models.CharField(max_length=50)),
                ('NIT', models.CharField(max_length=15)),
                ('GENERO', models.BooleanField()),
                ('TELEFONO', models.CharField(max_length=15)),
                ('CORREO_ELECTRONICO', models.CharField(max_length=50)),
                ('FECHA_NACIMIENTO', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='REP_TRABAJO',
            fields=[
                ('ID_TRABAJO', models.AutoField(primary_key=True, serialize=False)),
                ('FECHA_INICIAL', models.DateField()),
                ('FECHA_FINAL', models.DateField()),
                ('NOMBRE_PUESTO', models.CharField(max_length=50)),
                ('MES_PLANILLA', models.CharField(max_length=10)),
                ('SALARIO', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ID_EMPRESA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TRABAJO_EMPRESA', to='etls.rep_empresa')),
                ('ID_PERSONA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TRABAJO_PERSONA', to='etls.rep_persona')),
            ],
        ),
    ]
