# Generated by Django 4.0.4 on 2022-04-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('database', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=50)),
                ('databaseName', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
